### ISSUE TITLE
Comments missing for conversion values

### ISSUE THREAD

**Issue by priyanshi-gupta** [adafruit/Adafruit_nRF52_Arduino#168]
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/c44725b07867a6e6894b8582f22648761e21cb32/libraries/Bluefruit52Lib/examples/Hardware/adc_vbat/adc_vbat.ino#L37

Can someone help me add comments to specify what do these numbers signify in the conversion? I am trying to implement the code for a 3.6v battery and want to know how these levels change for that?

**Comment by hathach** [comment]
Hi, the person who wrote this code is current on vacation until September. You may want to post to our support forum, there are lots more user and support team there that could help you out.

https://forums.adafruit.com/viewforum.php?f=57

**Comment by Nenik** [comment]
The whole code block in that sample is a piece-wise linear interpolation between a set of fixed voltages.
You can imagine it as a table that assigns percentages to voltages, except that it works with ADC-measured voltages, as opposed to real battery voltages (the chip measures the voltage behind a resistive divider of 1:1.403, so that 3000mV at ADC would be 4209mV of battery and 100% charge.

For your battery, you'd have to find a relevant discharge curve, try to interpolate it with linear segments and pick your coeeficients accordingly.

**Comment by hathach** [comment]
this issue should already be explained by Nenik, if you still want more clarification. Please post on our support forum.
