### ISSUE TITLE
Bluefruit.Scanner caused high HID latency

### ISSUE THREAD

**Issue by shaoyuan1943** [adafruit/Adafruit_nRF52_Arduino#404]
I am using nRF52832 feather to build a wireless split keyboard(right handler is cent, right handler start scanner found left and connect it, PC is perph, right handler input to perph by HID). 

Recently I found a problem. **When Bluefruit.Scanner is turned on, the delay through HID input is very obvious. When Bluefruit.Scanner is turned off, HID input is normal.**

I don't know why and I tried some other ways but didn't solve the problem, my code like this:

```

BLEHidAdafruit    Hid;
void setup() {
  // ...
  Bluefruit.Scanner.setRxCallback(scanCallback);
  Bluefruit.Scanner.setStopCallback(scan_stop_callback);
  Bluefruit.Scanner.restartOnDisconnect(true);
  Bluefruit.Scanner.setInterval(160, 80);
  Bluefruit.Scanner.filterUuid(BLEUART_UUID_SERVICE);
  Bluefruit.Scanner.useActiveScan(false);
  // 0 = Don't stop scanning after n seconds
  //Bluefruit.Scanner.start(1200);
  Bluefruit.Scanner.start(12000);  
}


void loop() {
  // ...
  bool reported = Hid.keyboardReport(perph_conn_handle, mods, report);
}

```

**Comment by hathach** [comment]
This should be considered normal, since scanning make use of bluetooth radio as well. You should post this question to Nordic devzone, they could possibly provide more detail explanation.

PS: your right handler should detect and connect to the left right away. Then there is no need to scan furthermore, this should be only one-time deal only.
