### ISSUE TITLE
Homekit LightBulb example

### ISSUE THREAD

**Issue by mattiahalter** [adafruit/Adafruit_nRF52_Arduino#508]
First of all, many thanks for all the work you put into the Adafruit nrf52 project. I am currently trying to compile the homekit lightbulb ("Bluefruit52Lib/examples/Projects/homekit/homekit_lightbulb/homekit_lightbulb.ino") project for a nRF52 chip with Arduino. 
I am stuck at the point where it looks for a crypto key file:

 homekit_lightbulb.ino:L20 
`#define CRYPTO_KEYFILE   "/adafruit/homekit/key"`

or 

BLEHomekit/src/crypto/crypto.c: L37,38 
```
#define CRYPTO_KEYDIR    "/adafruit/homekit"
#define CRYPTO_KEYFILE   CRYPTO_KEYDIR "/key"
```

Where is this key file? Or whats the format if I have to create it myself? 
Thanks!

**Comment by hathach** [comment]
this file is store on the flash of nrf52 using the littleFS, you can access it using the Internal FileSystem library. The homekit example is obsolete, it may not compile, last time I worked with it. It can only passed the pairing/adding security (which is quite a lot of work by itself). Other session security is not implemented, since I don't have enough time to do it.
