### ISSUE TITLE
Bluetooth LE Mesh

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino#64]
https://www.bluetooth.com/what-is-bluetooth-technology/how-it-works/le-mesh

may requires BLE5 SoftDevice #46

**Comment by microbuilder** [comment]
Thanks for filing an issue.

I was reading the 1.0 spec last night, and it's limited since it's based entirely on advertising (which is due to a design limitation of BLE of course and the nature of connections), but I still think this is useful and it's good to have a standard for mesh based on inexpensive BLE devices since they are so plentiful, and unlike 802.15.4 they are generally compatible across manufacturers (though 15.4 is a much better basis for mesh, since it has reliable communication and you know when a message fails, etc.).

We should put a simple demo together for this down the road, though, since it could be useful in a home environment, and the nRF52 is reasonably affordable and allows you to connect to your mobile phone as a gateway or edge router to the sensor nodes.

**Comment by hathach** [comment]
sdk for mesh http://www.nordicsemi.com/eng/Products/Bluetooth-low-energy/nRF5-SDK-for-Mesh

**Comment by microbuilder** [comment]
https://devzone.nordicsemi.com/blogs/1147/introducing-nrf5-sdk-for-mesh/

**Comment by microbuilder** [comment]
Yeah, there's a misconception (that I had myself at first since the BLE Mesh announcement was timed with BLE5) that this is tied to the latest BLE spec, but that definitely isn't the case. Thanks for tossing that out to clarify though!

**Comment by hathach** [comment]
closed since it is not relevant anymore

**Comment by Krastanov** [comment]
@hathach , for reference could you say why it is not relevant anymore? I am subscribed for some updates on this project because I use it once a year and having mesh would make my life easier, but I have not tracked its progress in detail.

Is the project deprecated? Is mesh implemented somewhere else? Is this a "feature that will never be implemented"? A quick search through code and documentation did not show anything.

**Comment by hathach** [comment]
it is not on the plan anymore.
